# LAB_EXCEPTIONS


def additoin(x, y):
    x = 10
    y = 20
    print("Addition:", x + b)

try:
 additoin(10, 20)
 if True:
   print("the operation is successful")
except NameError as e:
 print(e) 
except Exception as e :
 print(e)